### ISSUE TITLE
Add missing reeds_shepp curve type in  reeds_shepp_path_planning.py 

### ISSUE THREAD

**Issue by oridong** [AtsushiSakai/PythonRobotics#341]
why there is curve type SLS  from function " straight_left_straight(x, y, phi) ". I read the paper but this type doesn't exist. 
Does this code  implement the algorithm completely? maybe it lacks the last five base words in the picture 
![image](https://user-images.githubusercontent.com/30712323/84746168-28ccb800-afe8-11ea-9ef1-b517937f3cdf.png)

**Comment by AtsushiSakai** [comment]
@oridong Hi. I don't remember it... maybe I used another paper or oss for implementation, not original paper.

>  maybe it lacks the last five base words in the picture
Yes, you are right. These should be implemented. Your PR is welcome : )

**Comment by lentychang** [comment]
Just for extra info:

Following your references, I found from table in page 135 in [this dissertation](https://homepages.laas.fr/jpl/promotion/chap3.pdf),
they propose more effective way to categorize all 48 combinations since these combinations don't all appear at same time. They can be categorized based on the orientation of car and orientation of steering angle (if I understand correctly).
